# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2
#      - name: Setup tmate (Debug) session
#        uses: mxschmitt/action-tmate@v3

      # Install requirements
      - name: Install requirements
        run: sudo apt update -y && sudo apt install -y git make texlive-extra-utils texlive-lang-arabic texlive-fonts-extra texlive-xetex texlive-science fonts-lmodern texlive-science-doc && echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install ttf-mscorefonts-installer && mkdir -p ~/.fonts ; cp ./fonts/* ~/.fonts/ ; fc-cache -f

      # Runs a set of commands using the runners shell
      - name: Compile LaTeX
        run: xelatex -interaction=nonstopmode 00

      - uses: actions/upload-artifact@v2
#     Maybe will be supported in the future
#        title: Build Artifacts
#          - files: [ "00.pdf" ]
#          - files: [ "00.log" ]

        with:
          name: Pdf Book
          path: ./00.pdf
